-- Synthetic sold-price history within the last 30 days so current_prices/net_profit
-- have data to derive from. Guarded by a row-count check in connection.py.
INSERT INTO price_history (part_id, price, source, date, condition, url) VALUES
('RAM-D4-8GB-DT',  13.50, 'eBay_sold', date('now','-3 days'),  'used', 'https://example.com/c/ram8-a'),
('RAM-D4-8GB-DT',  15.00, 'eBay_sold', date('now','-9 days'),  'used', 'https://example.com/c/ram8-b'),
('RAM-D4-8GB-DT',  14.25, 'eBay_sold', date('now','-18 days'), 'used', 'https://example.com/c/ram8-c'),
('RAM-D4-16GB-DT', 25.00, 'eBay_sold', date('now','-2 days'),  'used', 'https://example.com/c/ram16-a'),
('RAM-D4-16GB-DT', 27.50, 'eBay_sold', date('now','-7 days'),  'used', 'https://example.com/c/ram16-b'),
('RAM-D4-16GB-DT', 26.00, 'eBay_sold', date('now','-14 days'), 'used', 'https://example.com/c/ram16-c'),
('RAM-D4-16GB-LP', 23.00, 'eBay_sold', date('now','-5 days'),  'used', 'https://example.com/c/ramlp-a'),
('RAM-D4-16GB-LP', 24.50, 'eBay_sold', date('now','-12 days'), 'used', 'https://example.com/c/ramlp-b'),
('SSD-NVME-256',   17.00, 'eBay_sold', date('now','-4 days'),  'used', 'https://example.com/c/nvme256-a'),
('SSD-NVME-256',   19.00, 'eBay_sold', date('now','-11 days'), 'used', 'https://example.com/c/nvme256-b'),
('SSD-NVME-256',   18.25, 'eBay_sold', date('now','-21 days'), 'used', 'https://example.com/c/nvme256-c'),
('SSD-NVME-512',   31.00, 'eBay_sold', date('now','-3 days'),  'used', 'https://example.com/c/nvme512-a'),
('SSD-NVME-512',   33.50, 'eBay_sold', date('now','-10 days'), 'used', 'https://example.com/c/nvme512-b'),
('SSD-SATA-256',   15.50, 'eBay_sold', date('now','-6 days'),  'used', 'https://example.com/c/sata256-a'),
('SSD-SATA-256',   16.75, 'eBay_sold', date('now','-16 days'), 'used', 'https://example.com/c/sata256-b'),
('CPU-I5-10500',   68.00, 'eBay_sold', date('now','-2 days'),  'used', 'https://example.com/c/i5-a'),
('CPU-I5-10500',   72.00, 'eBay_sold', date('now','-8 days'),  'used', 'https://example.com/c/i5-b'),
('CPU-I5-10500',   70.50, 'eBay_sold', date('now','-19 days'), 'used', 'https://example.com/c/i5-c'),
('CPU-I7-10700',  115.00, 'eBay_sold', date('now','-4 days'),  'used', 'https://example.com/c/i7-a'),
('CPU-I7-10700',  124.00, 'eBay_sold', date('now','-13 days'), 'used', 'https://example.com/c/i7-b'),
('WIFI-AX200',     11.50, 'eBay_sold', date('now','-5 days'),  'used', 'https://example.com/c/ax200-a'),
('WIFI-AX200',     12.50, 'eBay_sold', date('now','-15 days'), 'used', 'https://example.com/c/ax200-b'),
('GPU-GT1030',     44.00, 'eBay_sold', date('now','-3 days'),  'used', 'https://example.com/c/gt1030-a'),
('GPU-GT1030',     47.00, 'eBay_sold', date('now','-12 days'), 'used', 'https://example.com/c/gt1030-b'),
('PSU-SFF-200',    21.00, 'eBay_sold', date('now','-7 days'),  'used', 'https://example.com/c/psu-a'),
('PSU-SFF-200',    23.00, 'eBay_sold', date('now','-17 days'), 'used', 'https://example.com/c/psu-b'),
('NIC-1G-DUAL',    14.00, 'eBay_sold', date('now','-6 days'),  'used', 'https://example.com/c/nic-a'),
('NIC-1G-DUAL',    16.00, 'eBay_sold', date('now','-20 days'), 'used', 'https://example.com/c/nic-b');
